// Per-character CheckPhone appearance customization (wallpaper + per-app icon overrides).
// Deliberately kept separate from CheckPhoneManifest: the manifest is regenerated by the
// AI on every "refresh signal" and fully overwritten (see generateCheckPhoneManifest /
// handleGenerate in checkphone-app.tsx), so anything stored there would be wiped out the
// next time the user refreshes a character's phone. Appearance is user-authored, not
// AI-generated, so it lives in its own kv-db-backed table keyed by characterId and
// survives manifest regeneration / clearing.

import { kvGet, kvSet, registerDynamicPrefix } from "./kv-db";
import type { CheckPhoneAppId } from "./checkphone-config";

const CHECKPHONE_APPEARANCE_PREFIX = "checkphone-appearance_";

registerDynamicPrefix(CHECKPHONE_APPEARANCE_PREFIX);

export type CheckPhoneAppearance = {
  characterId: string;
  /** URL or data: URL. Applied as the fullscreen simulator background. */
  wallpaperUrl: string | null;
  /** Zoom, in percent. 100 = fit-cover at natural scale. */
  wallpaperScale: number;
  /** Horizontal pan, in percent of container width. 0 = centered. */
  wallpaperOffsetX: number;
  /** Vertical pan, in percent of container height. 0 = centered. */
  wallpaperOffsetY: number;
  /** Per-app custom icon image, keyed by CheckPhoneAppId. URL or data: URL. */
  iconOverrides: Partial<Record<CheckPhoneAppId, string>>;
  /** Custom text color for app labels and widget captions on the home screen. CSS color string or null for default. */
  labelColor: string | null;
  updatedAt: string;
};

function appearanceKey(characterId: string): string {
  return `${CHECKPHONE_APPEARANCE_PREFIX}${characterId}`;
}

function emptyAppearance(characterId: string): CheckPhoneAppearance {
  return {
    characterId,
    wallpaperUrl: null,
    wallpaperScale: 100,
    wallpaperOffsetX: 0,
    wallpaperOffsetY: 0,
    iconOverrides: {},
    labelColor: null,
    updatedAt: new Date().toISOString(),
  };
}

export function loadCheckPhoneAppearance(characterId: string): CheckPhoneAppearance {
  if (!characterId) return emptyAppearance(characterId);
  try {
    const raw = kvGet(appearanceKey(characterId));
    if (!raw) return emptyAppearance(characterId);
    const parsed = JSON.parse(raw) as Partial<CheckPhoneAppearance>;
    return {
      characterId,
      wallpaperUrl: typeof parsed.wallpaperUrl === "string" && parsed.wallpaperUrl.trim() ? parsed.wallpaperUrl : null,
      wallpaperScale: typeof parsed.wallpaperScale === "number" && parsed.wallpaperScale > 0 ? parsed.wallpaperScale : 100,
      wallpaperOffsetX: typeof parsed.wallpaperOffsetX === "number" ? parsed.wallpaperOffsetX : 0,
      wallpaperOffsetY: typeof parsed.wallpaperOffsetY === "number" ? parsed.wallpaperOffsetY : 0,
      iconOverrides:
        parsed.iconOverrides && typeof parsed.iconOverrides === "object" ? { ...parsed.iconOverrides } : {},
      labelColor: typeof parsed.labelColor === "string" && parsed.labelColor.trim() ? parsed.labelColor : null,
      updatedAt: typeof parsed.updatedAt === "string" ? parsed.updatedAt : new Date().toISOString(),
    };
  } catch {
    return emptyAppearance(characterId);
  }
}

export function saveCheckPhoneAppearance(appearance: CheckPhoneAppearance): void {
  if (!appearance.characterId) return;
  kvSet(appearanceKey(appearance.characterId), JSON.stringify(appearance));
}

export function setCheckPhoneWallpaper(characterId: string, wallpaperUrl: string | null): CheckPhoneAppearance {
  const current = loadCheckPhoneAppearance(characterId);
  const cleared = !wallpaperUrl || !wallpaperUrl.trim();
  const next: CheckPhoneAppearance = {
    ...current,
    wallpaperUrl: cleared ? null : wallpaperUrl.trim(),
    // Reset pan/zoom whenever the image itself is cleared or swapped, so a new
    // image doesn't inherit an old crop that no longer makes sense.
    wallpaperScale: cleared ? 100 : current.wallpaperScale,
    wallpaperOffsetX: cleared ? 0 : current.wallpaperOffsetX,
    wallpaperOffsetY: cleared ? 0 : current.wallpaperOffsetY,
    updatedAt: new Date().toISOString(),
  };
  saveCheckPhoneAppearance(next);
  return next;
}

export function setCheckPhoneWallpaperTransform(
  characterId: string,
  transform: Partial<Pick<CheckPhoneAppearance, "wallpaperScale" | "wallpaperOffsetX" | "wallpaperOffsetY">>,
): CheckPhoneAppearance {
  const current = loadCheckPhoneAppearance(characterId);
  const next: CheckPhoneAppearance = {
    ...current,
    ...transform,
    updatedAt: new Date().toISOString(),
  };
  saveCheckPhoneAppearance(next);
  return next;
}

export function setCheckPhoneIconOverride(
  characterId: string,
  appId: CheckPhoneAppId,
  iconUrl: string | null,
): CheckPhoneAppearance {
  const current = loadCheckPhoneAppearance(characterId);
  const nextIcons = { ...current.iconOverrides };
  if (iconUrl && iconUrl.trim()) {
    nextIcons[appId] = iconUrl.trim();
  } else {
    delete nextIcons[appId];
  }
  const next: CheckPhoneAppearance = {
    ...current,
    iconOverrides: nextIcons,
    updatedAt: new Date().toISOString(),
  };
  saveCheckPhoneAppearance(next);
  return next;
}

export function setCheckPhoneLabelColor(characterId: string, color: string | null): CheckPhoneAppearance {
  const current = loadCheckPhoneAppearance(characterId);
  const next: CheckPhoneAppearance = {
    ...current,
    labelColor: color && color.trim() ? color.trim() : null,
    updatedAt: new Date().toISOString(),
  };
  saveCheckPhoneAppearance(next);
  return next;
}

export function resetCheckPhoneAppearance(characterId: string): CheckPhoneAppearance {
  const next = emptyAppearance(characterId);
  saveCheckPhoneAppearance(next);
  return next;
}
